version: "3.9"

networks:
    laravel:
        name: laravel

services:

    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        depends_on:
            - php
            - mysql
        container_name: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./src:/var/www/html
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./src:/var/www/html
        depends_on:
            - mysql
            - npm
        networks:
            - laravel

    mysql:
        image: mysql:8.0.27
        container_name: mysql
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - laravel

    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel
        command: tail -f /dev/null

    npm:
        image: node:current-alpine
        container_name: npm
        ports:
            - 5173:5173
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        command: npm run dev --host
        networks:
            - laravel
    elasticsearch:
        image: elasticsearch:8.11.3
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
        ports:
            - 9200:9200
            - 9300:9300
        networks:
            - laravel
    kibana:
        image: kibana:8.11.3
        container_name: kibana
        ports:
            - 5601:5601
        environment:
            - elasticsearch.hosts=["http://elasticsearch:9200"]
            - xpack.security.enabled=false
        networks:
            - laravel